Bug/175/wrong spawn
courselab/coral pull request #176
Opened 2024-12-11 14:28 UTC by rodrigo-lex

fixing #175

2024-12-11 18:13 UTC, rodrigo-lex commented
> Você está dando merge direto pra main.

corrigido!

2024-12-11 18:46 UTC, de-abreu commented
Tested it locally and it looks good.

2024-12-12 00:59 UTC, laurafcamargos approved these changes
I think its solved.

2024-12-12 21:58 UTC, joaoprfreitas approved these changes

2024-12-13 21:03 UTC, raultel commented
Somehow I'm still running into to bug, I'll send a screenshot of the game state:
![Screenshot_2024-12-13_17-59-25](https://github.com/user-attachments/assets/c737abbc-03ce-4aba-8615-c69edaddc320)

2024-12-13 21:16 UTC, raultel requested changes

2024-12-13 21:16 UTC, raultel commented on app/main.py
Since the bug still appears to happen I recommend testing if the apples x and y coordinates being changed outside their class really has any effect.

2024-12-15 06:26 UTC, liestrela commented
`apple.x = obstacle.x - 1 % size...` doesn't quite solve the issue. `1 % x` is 1 $\forall x>0$, so this line just shifts the apple one pixel to the left. So I just added a new method on `BaseFruit` that recalculates the fruit position. It is called repeatedly until the fruit and obstacle doesn't overlap.

2024-12-15 06:27 UTC, raultel approved these changes
looks like its working now!

2024-12-15 06:32 UTC, raultel requested changes
there may be an edge case where the new position conflicts with a previous obstacle

2024-12-15 07:40 UTC, liestrela commented
LGTM, but I think it should be reviewed again. Some subtle changes like this (that involves random stuff) require more pragmatic testing.

2024-12-15 19:51 UTC, rodrigo-lex reviewed
last commit seems to have finally (and correctly) fixed this.

2024-12-15 22:46 UTC, merged