code: adding static obstacles
courselab/coral pull request #27
Opened 2024-11-04 23:39 UTC by laurafcamargos

2024-11-12 23:13 UTC, roselino-quatro requested changes
- Sometimes the apple spawns inside one of the obstacles, softlocking the game
- Currently the obstacles can spawn inside each other (its easier to test this by increasing the amount of obstacles temporarily)
- the snake spawn point can be inside a obstacle, making the game impossible to play
- it would make sense creating a option to start a game without obstacles, but maybe its more fitting to do it in a separate issue

2024-11-12 23:15 UTC, roselino-quatro commented on coral.py
> +        pygame.draw.rect(arena, "#FF4500", self.rect)  # Use orange color for obstacles.
perhaps creating a constant for the obstacle color would fit better in the current code style, like we are already doing with the other objects colors

2024-11-13 10:35 UTC, laurafcamargos reviewed
The comments made and the suggested change are in agreement.

2024-12-04 23:27 UTC, laurafcamargos reviewed
Added logic to check if the snake's head collides with an obstacle, added drawing of obstacles in the main game loop, initial generation of obstacles, and created a function to generate a list of obstacles based on the specified number. This enables the generation of multiple obstacles either at the start of the game or during its execution.

2024-12-05 15:01 UTC, closed without merging