doc: add installation instructions to README
courselab/coral pull request #81
Opened 2024-11-14 00:16 UTC by guisp03

This pull request addresses issue #77 by adding a new section to the README.md with installation instructions for the game. The instructions include:
- Prerequisites, such as Python 3 and the Pygame engine.
- Step-by-step guidance for installing Pygame, covering both pip and alternative package managers (e.g., pacman for Arch-based systems).
- Instructions on how to clone the repository, navigate to the project folder, and run the game using the coral.py file.

These additions aim to provide a clear and accessible guide for new developers or users unfamiliar with Python and Pygame, ensuring an easier setup process.

2024-11-14 02:14 UTC, ImLusca requested changes

2024-11-14 02:14 UTC, ImLusca commented on README.md
> + - Python 3: Make sure you have Python 3 installed on your machine. You can download it from the official Python website.
Add python download link using `download it from the official Python [website](https://www.python.org/downloads/)`

2024-11-14 02:14 UTC, ImLusca commented on README.md
> + - Python 3: Make sure you have Python 3 installed on your machine. You can download it from the official Python website.
Add the apt install command for linux users

2024-11-14 02:14 UTC, ImLusca commented on README.md
> + git clone https://github.com/your-username/coral.git
github http auth is deprecated. Use SSH instead

2024-11-19 00:21 UTC, guisp03 commented
Hi @ImLusca , I’ve made the requested changes:
- Added the Python download link for Windows/Mac users.
- Included the `apt install` command for Linux users with a note on distribution differences.
- Updated the clone command to SSH.
Let me know if there’s anything else to adjust. Thanks for the feedback!

2024-11-20 23:22 UTC, samuks123 approved these changes
All the requested changes have been resolved

2024-11-22 17:14 UTC, merged